Feature/alter model fields for extra functionality
maykinmedia/django-timeline-logger pull request #9
Opened 2018-03-13 12:05 UTC by tsiaGeorge

2018-03-13 16:13 UTC, sergei-maertens requested changes
Can you squash the migrations into a single migration?

2018-03-14 11:59 UTC, holms commented
@tsiaGeorge I'd buy you a bear for this fix, really :)

2018-03-15 09:49 UTC, tsiaGeorge commented
@holms I hope it's vegetarian :)

2018-03-15 15:18 UTC, sergei-maertens approved these changes

2018-03-15 15:18 UTC, merged